-- Create secured schemas
CREATE SCHEMA IF NOT EXISTS STAGING WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS SILVER  WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS GOLD    WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS AUDIT   WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS UTIL    WITH MANAGED ACCESS;

-- Transfer OWNERSHIP
GRANT OWNERSHIP ON SCHEMA STAGING TO DATABASE ROLE DBR_ADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SILVER  TO DATABASE ROLE DBR_ADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA GOLD    TO DATABASE ROLE DBR_ADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA AUDIT   TO DATABASE ROLE DBR_ADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA UTIL    TO DATABASE ROLE DBR_ADMIN REVOKE CURRENT GRANTS;

-- Grant priviledges
GRANT USAGE ON SCHEMA STAGING TO DATABASE ROLE DBR_READ;
GRANT USAGE ON SCHEMA STAGING TO DATABASE ROLE DBR_WRITE;
GRANT USAGE ON SCHEMA SILVER  TO DATABASE ROLE DBR_WRITE;
GRANT USAGE ON SCHEMA SILVER  TO DATABASE ROLE DBR_READ;
GRANT USAGE ON SCHEMA GOLD    TO DATABASE ROLE DBR_READ;
GRANT USAGE ON SCHEMA AUDIT   TO DATABASE ROLE DBR_READ;

GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING TO DATABASE ROLE DBR_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUDIT TO DATABASE ROLE DBR_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SILVER TO DATABASE ROLE DBR_READ;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GOLD   TO DATABASE ROLE DBR_READ;

GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STAGING TO DATABASE ROLE DBR_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SILVER  TO DATABASE ROLE DBR_WRITE;