-- Snowflake Scripting : n'exécute l'attach que si la vue existe
USE SCHEMA GOLD;

ALTER VIEW IF EXISTS DIM_MAGASINS
    DROP ALL ROW ACCESS POLICIES;
ALTER VIEW IF EXISTS DIM_MAGASINS
    ADD ROW ACCESS POLICY RLS_BY_BRAND ON (BRAND);

-- ALTER VIEW IF EXISTS DIM_MAGASINS
--     MODIFY COLUMN NAME
--     UNSET MASKING POLICY;
-- ALTER VIEW IF EXISTS DIM_MAGASINS
--     MODIFY COLUMN NAME
--     SET MASKING POLICY MASK_NAME_BY_BRAND USING (NAME, BRAND);
