-- Technical roles
CREATE DATABASE ROLE IF NOT EXISTS DBR_READ;
CREATE DATABASE ROLE IF NOT EXISTS DBR_WRITE;
CREATE DATABASE ROLE IF NOT EXISTS DBR_ADMIN;

-- Functional persona roles
CREATE DATABASE ROLE IF NOT EXISTS DBR_DATA_ENGINEER;
CREATE DATABASE ROLE IF NOT EXISTS DBR_DATA_ANALYST;

-- Brands roles
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_MONOPRIX;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_CARREFOUR;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_LECLERC;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_INTERMARCHE;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_SUPER_U;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_CASINO;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_AUCHAN;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_METRO_AG;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_SEPHORA;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_FRANPRIX;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_BEAUTY_SUCCES;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_GALERIES_LAFAYETTE;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_NOCIBE;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_LEROY_MERLIN;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_MR_BRICOLAGE;
CREATE DATABASE ROLE IF NOT EXISTS DBR_BRAND_MARIONNAUD;
CREATE DATABASE ROLE IF NOT EXISTS DBR_ROLE_CASINO_GROUP;
CREATE DATABASE ROLE IF NOT EXISTS DBR_ROLE_AFM;

-- Role composition grants
GRANT DATABASE ROLE DBR_WRITE TO DATABASE ROLE DBR_DATA_ENGINEER;
GRANT DATABASE ROLE DBR_READ  TO DATABASE ROLE DBR_DATA_ENGINEER;

GRANT DATABASE ROLE DBR_READ  TO DATABASE ROLE DBR_DATA_ANALYST;

GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_MONOPRIX;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_CARREFOUR;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_LECLERC;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_INTERMARCHE;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_SUPER_U;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_CASINO;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_AUCHAN;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_METRO_AG;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_SEPHORA;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_FRANPRIX;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_BEAUTY_SUCCES;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_GALERIES_LAFAYETTE;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_NOCIBE;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_LEROY_MERLIN;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_MR_BRICOLAGE;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_BRAND_MARIONNAUD;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_ROLE_CASINO_GROUP;
GRANT DATABASE ROLE DBR_READ TO DATABASE ROLE DBR_ROLE_AFM;

GRANT DATABASE ROLE DBR_ADMIN TO ROLE ROLE_YANNICK_RADJI;