-- Attach policies to gold view if it exists A FAIRE DANS DBT ou executer après lui
BEGIN
  IF (EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA='GOLD' AND TABLE_NAME='DIM_MAGASINS')) THEN
    ALTER VIEW GOLD.DIM_MAGASINS ADD ROW ACCESS POLICY RLS_BY_BRAND ON (name);
    ALTER VIEW GOLD.DIM_MAGASINS MODIFY COLUMN name SET MASKING POLICY MASK_NAME_BY_ROLE;
  END IF;
END;