version: 2

sources:
  - name: DTL_EXO_GI
    database: DTL_EXO
    schema: GI
    tables:
      - name: MAGASINS
    config:
      freshness: { warn_after: { hours: 24 } }
  - name: DTL_EXO_TH
    database: DTL_EXO
    schema: TH
    tables:
      - name: MAGASINS
    config:
      freshness: { warn_after: { hours: 24 } }
